### PR TITLE
Add more vendored deps required for `dep-collector` 🤣

### PR DESCRIPTION
**Pull request by bobcatfish**
In #485 (#290 in build-pipeline)  I tried to fix the logic that automatically installs
`dep-collector` when it is not present on your system, but it looks like
I missed at least one dependency.

I think it is deeply ironic that we have to manually collect and add the
dependencies for a tool called `dep-collector` which is supposed to be
make it easy to managed deps 🤣

^^ Or am I doing something wrong?????

```release-note
NONE
```

Corresponds to https://github.com/knative/build-pipeline/pull/293

### CODE REVIEW

**Comment by mattmoor** [comment]
`go get` grabs HEAD, which has been notorious for breaking the Kubernetes folks (at least when outside of their control), and co-versioning via vendoring is a way to fix that.  That said, you don't want to add `dep-collector`'s dependencies, I think you'd want to add it to the list of `required = []` tools in `Gopkg.toml`.

**Comment by adrcunha** [comment]
https://github.com/knative/build-pipeline/pull/296 should make things easier.

**Comment by bobcatfish** [comment]
> That said, you don't want to add dep-collector's dependencies, I think you'd want to add it to the list of required = [] tools in Gopkg.toml.

@mattmoor will that make it grab the dependencies as well? and does that mean we can remove the dependencies from the .lock file as well - or does it just imply that `go dep` will manage those dependencies in the .lock file?

**Comment by bobcatfish** [comment]
I think even with #489 we need this - I tried:
1. Deleting `licenseclassifier` and `go-diff` from the `Gopkg.lock` and from the `vendor` dir
2. Removing my `dep-collector` binary
3. Running `hack/update-deps.sh`

`go dep` didn't pick up the dependencies needed for `dep-collector` b/c I ended up with:

```
vendor/github.com/knative/test-infra/tools/dep-collector/licenses.go:28:2: cannot find package "github.com/google/licenseclassifier" in any of:
	/usr/local/google/home/christiewilson/Code/go/src/github.com/knative/build-pipeline/vendor/github.com/google/licenseclassifier (vendor tree)
	/usr/lib/google-golang/src/github.com/google/licenseclassifier (from $GOROOT)
	/usr/local/google/home/christiewilson/Code/go/src/github.com/google/licenseclassifier (from $GOPATH)
```

It seems like we still need to manually add the dependencies?

**Comment by bobcatfish** [comment]
> @bobcatfish Adding it to required should be all you need, unless you need to pin specific versions.

well it didn't work for me @mattmoor but ill close this for now and reopen if god forbid this happens again

**Pull request closed without merging**
