### PR TITLE
Consume the simplified controller constructor.

### PR DESCRIPTION
**Pull request by mattmoor**
See also: knative/pkg#427

/hold

This is RFAL, but shouldn't merge until the upstream change lands and this is reworked to consume it.

### CODE REVIEW

**Comment by mattmoor** [comment]
@ImJasonH I think the e2e test failure may be because Build is way behind on knative/pkg.  Can you TAL?

**Comment by ImJasonH** [comment]
> @ImJasonH I think the e2e test failure may be because Build is way behind on knative/pkg. Can you TAL?

Just getting back to this now. It looks like the webhook controller isn't being registered, so no validation is happening at all:

```
{"level":"error","logger":"webhook","caller":"webhook/webhook.go:296","msg":"failed to register webhook","knative.dev/controller":"webhook","error":"failed to fetch our deployment: deployments.apps \"build-webhook\" is forbidden: User \"system:serviceaccount:knative-build:build-controller\" cannot get deployments.apps in the namespace \"knative-build\"","stacktrace":"github.com/knative/build/vendor/github.com/knative/pkg/webhook.(*AdmissionController).Run\n\t/usr/local/google/home/jasonhall/go/src/github.com/knative/build/vendor/github.com/knative/pkg/webhook/webhook.go:296\nmain.main\n\t/usr/local/google/home/jasonhall/go/src/github.com/knative/build/cmd/webhook/main.go:92\nruntime.main\n\t/usr/lib/google-golang/src/runtime/proc.go:200"}
```

Do you know any recent changes to knative/pkg that might be the culprit? Tests pass at knative/build head, using knative/pkg from March.

**Comment by mattmoor** [comment]
@ImJasonH I bet is was a change from beta apps to v1 apps, so changing the RBAC should fix this.

**Comment by ImJasonH** [comment]
Superceded by #615

**Pull request closed without merging**
