### PR TITLE
[WIP] Check the integration test after replace DOCKER_REPO_OVERRIDE by KO_DOCKER_REPO and delete K8S_* vars in test-infra

### PR DESCRIPTION
**Pull request by zxDiscovery**
## Proposed Changes

`DOCKER_REPO_OVERRIDE` replaced by `KO_DOCKER_REPO` and delete K8S_* vars in test-infra.
Update the `vendor` folder manually to test ensure the integration test pass. https://github.com/knative/test-infra/pull/481

/cc @adrcunha

### CODE REVIEW

**Comment by zxDiscovery** [comment]
The `pull-knative-build-integration-tests` test result passed. @adrcunha

**Comment by adrcunha** [comment]
Great, let's move forward. Once test-infra is updated, repurpose this PR to properly update test-infra and all tests should pass.

**Comment by adrcunha** [comment]
Obsoleted by https://github.com/knative/build

**Pull request closed without merging**
