### PR TITLE
Update pkg

### PR DESCRIPTION
**Pull request by shashwathi**
## Proposed Changes

  *Update pkg to serving HEAD

### CODE REVIEW

**Comment by ImJasonH** [comment]
Was there something from pkg you were hoping to get?

**Comment by shashwathi** [comment]
I started addressing [this](https://github.com/knative/build/issues/378) issue and I did not want to update pkg as well in same issue. This PR is just suppose to provide some ground work.

**Comment by ImJasonH** [comment]
Cool cool. Thanks!

/lgtm

**Pull request merged**
