### PR TITLE
enqueue again after the build timeout

### LINKED ISSUE #332: Timeout of build may have problem
/area test-and-release
/kind bug
/kind dev

## Expected Behavior

the job resource in kuberenets has an active deadline seconds (ADS), it can be said that, the timeout of build controller is very similar to it

currently, build controller handle a build info from the `workqueue` and the workqueue is fill by build informer, aka when 

* user create / update a build resource
* pod changes
* informer resync happen ( resync period is not 0)

and the resync time is set to 30s

https://github.com/knative/build/blob/4dfa5dabd59de26ef5607b02ac7a536cfb05ecea/cmd/controller/main.go#L91

so if the build timeout is less than 30s, the build may live longer than actual timeout time

## Additional Info

kubernetes job controller relative issues [Too long time needed for a job to be killed after exceeding relatively short ActiveDeadlineSeconds](https://github.com/kubernetes/kubernetes/issues/32149)

### PR DESCRIPTION
**Pull request by zrss**
Fixes #332 

## Proposed Changes

  * enqueue a build item again after it timeout

**Release Note**

```release-note
enqueue a build item again after it timeout
```

### CODE REVIEW

**Comment by zrss** [comment]
@ImJasonH  yes, it needs sometime to cover it

**Comment by zrss** [comment]
@ImJasonH PTAL, free to review it

**Comment by ImJasonH** [comment]
@zrss There's been a bit of churn since this PR was proposed, do you think you'd be interested in rebasing to pick up the changes and resolve conflicts?

**Comment by zrss** [comment]
eh.. quite a long time. i took a long vacation and will go on it soon

Jason Hall <notifications@github.com> 于2018年10月6日周六 上午4:53写道：

**Comment by zrss** [comment]
/lint

@ImJasonH It took some time to get back the idea ... PTAL

**Comment by zrss** [comment]
kindly ping @ImJasonH

**Comment by zrss** [comment]
:sweat_smile:, another long dumb time, and actually there maybe huge changes about this code, so i close it now (and a pending PR drives me mad)

if there still has the problem, and this could be a hint to fix it @ImJasonH

**Pull request closed without merging**
