### PR TITLE
Update links to docs repo

### PR DESCRIPTION
**Pull request by samodell**
Work towards fixing https://github.com/knative/docs/issues/1038

## Proposed Changes

* Updates all links in the Build repo that began with github.com/knative/docs

### CODE REVIEW

**Comment by ImJasonH** [comment]
This PR shouldn't update files in `vendor/`, since those changes will be undone the next time we update that vendor. Instead, those changes should be made in the other repo and vendored in using `./hack/update-deps.sh`.

**Comment by samodell** [comment]
@ImJasonH  Could you point me to the repo where that vendor content comes from?

**Comment by ImJasonH** [comment]
> @ImJasonH Could you point me to the repo where that vendor content comes from?

https://github.com/knative/caching/

If you update that repo we can update our vendor of that repo in this or a future PR to pick up those changes.

**Comment by samodell** [comment]
@ImJasonH  removed the updates to the vendor files from this PR.

**Pull request merged**
