### PR TITLE
Add support for setting environment variables on git init container

### PR DESCRIPTION
**Pull request by shashwathi**
This change will allow build to use git repositories behind corporate firewalls
or any proxy sites.

Partially addresses #423 

## Proposed Changes

  * Git source takes `env` key. 
  * All variables under `env` will be set on init container
 

**Release Note**

```
Set environment variables like proxy variables on git init containers.
```

* No e2e test in this PR
  
   I have added only unit tests for this feature. I am not aware of any git URLs which is behind firewall so if anybody has ideas about adding e2e test which uses environment variable feel free to comment on this PR. I am happy to update with integration test.

cc @ImJasonH @mattmoor

### CODE REVIEW

**Comment by shashwathi** [comment]
@DanielJonesEB @andrewdriver123 let me know if this solution helps you with #423 issue. I would love to hear your thoughts.

**Comment by mattmoor** [comment]
@shashwathi with this can the url contain env vars?  if so, you can write an e2e test :)

**Comment by shashwathi** [comment]
@mattmoor 
I like that idea. Gives me an opportunity to test for sure. Outside of testing, Is there any real use case for templating url parts from env vars?
ex: Is there a world where github URL would be fetched from secret/configMap?

**Comment by fejta** [comment]
Wouldn't it be better for source to use a higher level abstraction than env var?

I would think this provides too tight a coupling with the internal of the git container. It would seem better for people who need this to use a custom clone container, which already allows setting env vars.

**Pull request closed without merging**
