### PR TITLE
Show additional build state info in CLI

### LINKED ISSUE #233: Need to return build status in UX CLI output
/area API
/kind dev

From a UX perspective `kubectl get builds` should return a status of sorts:

```
$ kubectl get builds
NAME          CREATED AT
hello-build   9m
```

Maybe a `COMPLETED` column with the number of completed steps.

### PR DESCRIPTION
**Pull request by greghaynes**
Add 'completed' column to 'get' cli to clearly indicate whether a build
has completed. Also add 'completed steps' field which can be used to
more easily determine current build status.

Fixes #233

**Release Note**

```release-note 
Add completed column and stepsCompleted to CLI
```

### CODE REVIEW

**Comment by ImJasonH** [comment]
It looks like this was added in Kubernetes 1.11, can we assume clients prior to that will just ignore this new information?

**Comment by greghaynes** [comment]
Good question - I just tested out a ko apply using kubectl v1.9.9 and it succeeded while ignoring the additional columns when doing a get.

**Comment by greghaynes** [comment]
I signed it!

**Comment by mattmoor** [comment]
Related: https://github.com/knative/serving/issues/1138

**Pull request merged**
